[build-system]
requires = ["flit_core >=3.6,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "biolopy"
authors = [{name = "Watal M. Iwasaki", email = "heavywatal@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
dynamic = ["description", "version"]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.10"
dependencies = [
  "tomli>=2.0"
]

[project.optional-dependencies]
test = [
  "pyproject-flake8",
  "pytest",
]

[project.urls]
source = "https://github.com/heavywatal/biolopy"

[tool.pyright]
typeCheckingMode = "strict"

[tool.flake8]
max-line-length = 88

[tool.pytest.ini_options]
testpaths = "tests"
